services:
  - type: web
    name: unfiltereduk
    env: node
    plan: free
    buildCommand: pnpm install
    startCommand: pnpm start
    autoDeploy: true
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000